### PR TITLE
Add divider and dropdown header to menu list

### PR DESCRIPTION
**Pull request by rudenyl**
Please add dropdown header and divider to dropdown menus.
group_select_context
header_and_divider

### CODE REVIEW

**Comment by wenzhixin** [comment]
Thanks for your Pull Request, can you show me how to use?

**Comment by rudenyl** [comment]
Hi Zhi,
Basically on the "data-data" attribute (where we list down our items), we just have to add a pipe-separated context  '|'  to list the key/value pair. For the dropdown header, we have the header title on the left side and the 'type' on the right (ie,  Dropdown Header Text|header). Now, for the divider, we only have the type (ie,  |divider). I have attached an image on the usage on my first post. Hope that helps. And maybe, you could do something better :)

**Comment by wenzhixin** [comment]
Great! Thanks :+1:

**Comment by rudenyl** [comment]
Cool. Thanks Zhi!

**Pull request merged**
